config/routes.rb
Eligant::Application.routes.draw do
  resources :news

  resources :dashboards

  root :to =>  "dashboards#index"

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/news.rb
class News < ActiveRecord::Base
   attr_accessible :title, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  # GET /dashboards
  # GET /dashboards.json
  def index
    @dashboards = Dashboard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dashboards }
    end
  end

  # GET /dashboards/1
  # GET /dashboards/1.json
  def show
    @dashboard = Dashboard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dashboard }
    end
  end

  # GET /dashboards/new
  # GET /dashboards/new.json
  def new
    @dashboard = Dashboard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dashboard }
    end
  end

  # GET /dashboards/1/edit
  def edit
    @dashboard = Dashboard.find(params[:id])
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    @dashboard = Dashboard.new(params[:dashboard])

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully created.' }
        format.json { render json: @dashboard, status: :created, location: @dashboard }
      else
        format.html { render action: "new" }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dashboards/1
  # PUT /dashboards/1.json
  def update
    @dashboard = Dashboard.find(params[:id])

    respond_to do |format|
      if @dashboard.update_attributes(params[:dashboard])
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard = Dashboard.find(params[:id])
    @dashboard.destroy

    respond_to do |format|
      format.html { redirect_to dashboards_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/application/_footer.html.haml
%div{:class=>"footer"}

app/views/application/_header.html.haml
%div{:class=>"head"}


  %div{:class=>"logo"}
    %a{:href=>"/"}
      %img{:src=>"/images/elegant-logo.png"}
  %a{:href=>"#", :id=>"expand", :class=> "i_login", :onclick=>"toggle('login-form');" }
    -#%div{:id=> "login-form"}
    -#  %label Login:
    -#  %input{:type=>'text'}
    -#  %br
    -#  %label Password:
    -#  %input{:type=>'password'}
    -#  %br
    -#  %input{:type=>'submit', :value=>'Login'}
    -#  %a{:href=>'#'} Forgot password?

%div{:class=>"nav"}
  %ul{:class=>"nav-items"}
    %li{:class => "current"}
      %i{:class=>"i_news"}
      %a{:href=>"#"} Новости
    %li{:class => ""}
      %i{:class=>"i_programm"}
      %a{:href=>"#"} Программы
    %li
      %i{:class=>"i_game"}
      %a{:href=>"#"} Игры
    %li
      %i{:class=>"i_film"}
      %a{:href=>"#"} Фильмы
    %li
      %i{:class=>"i_musik"}
      %a{:href=>"#"} Музыка
    %li
      %i{:class=>"i_forum"}
      %a{:href=>"#"} Форум
    %li{:class => "last"}
      %i{:class=>"i_profile"}
      %a{:href=>"#"} Профиль

app/views/application/_left_side.html.haml
.left-side-content
  .left-side-head
  .left-side-inner
  .left-side-footer

.left-side-content
  .left-side-head
  .left-side-inner
  .left-side-footer

.left-side-content
  .left-side-head
  .left-side-inner
  .left-side-footer

app/views/dashboards/_form.html.haml
= form_for @dashboard do |f|
  - if @dashboard.errors.any?
    #error_explanation
      %h2= "#{pluralize(@dashboard.errors.count, "error")} prohibited this dashboard from being saved:"
      %ul
        - @dashboard.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/dashboards/edit.html.haml
%h1 Editing dashboard

= render 'form'

= link_to 'Show', @dashboard
\|
= link_to 'Back', dashboards_path

app/views/dashboards/index.html.haml
-#%div{:class=>"container"}
-#  #content
-#    .col1
-#    .spin
-#    .col2

app/views/dashboards/new.html.haml
%h1 New dashboard

= render 'form'

= link_to 'Back', dashboards_path

app/views/dashboards/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_dashboard_path(@dashboard)
\|
= link_to 'Back', dashboards_path

app/views/layouts/application.html.haml
!!!
%html
  %head

    %title Eligant
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %div{:class=>'content'}
      = render "header"
      %div{:class=>'main'}
        %div{:class=>"container"}
          #content
            .col1
              = render "left_side"
            .spin
            .col2
              = yield
      = render "footer"

app/views/news/_form.html.haml
= form_for @news do |f|
  - if @news.errors.any?
    #error_explanation
      %h2= "#{pluralize(@news.errors.count, "error")} prohibited this news from being saved:"
      %ul
        - @news.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/news/edit.html.haml
%h1 Editing news

= render 'form'

= link_to 'Show', @news
\|
= link_to 'Back', news_index_path

app/views/news/index.html.haml
%div{:class=>"container"}
  - @news.each do |news|
    %div{:class=>'news'}
      %div{:class=>'news-title'}
        %h1= news.title
      %div{:class=>'news-description'}
        %h1= news.description
      %div{:class=>'news-footer'}
        %h1= news.created_at

app/views/news/new.html.haml
%h1 New news

= render 'form'

= link_to 'Back', news_index_path

app/views/news/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_news_path(@news)
\|
= link_to 'Back', news_index_path